// Code generated by "stringer -type=APIErrorCode -output=types_err.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrOversizedPiece-4011]
	_ = x[ErrStorageProviderSuspended-4012]
	_ = x[ErrStorageProviderIneligibleToMine-4013]
	_ = x[ErrUnclaimedPieceCID-4020]
	_ = x[ErrProviderHasReplica-4021]
	_ = x[ErrTenantsOutOfDatacap-4022]
	_ = x[ErrTooManyReplicas-4023]
	_ = x[ErrProviderAboveMaxInFlight-4024]
	_ = x[ErrReplicationRulesViolation-4029]
	_ = x[ErrExternalReservationRefused-4030]
	_ = x[ErrInvalidRequest-4400]
	_ = x[ErrUnauthorizedAccess-4401]
	_ = x[ErrSystemTemporarilyDisabled-4503]
}

const (
	_APIErrorCode_name_0 = "ErrOversizedPieceErrStorageProviderSuspendedErrStorageProviderIneligibleToMine"
	_APIErrorCode_name_1 = "ErrUnclaimedPieceCIDErrProviderHasReplicaErrTenantsOutOfDatacapErrTooManyReplicasErrProviderAboveMaxInFlight"
	_APIErrorCode_name_2 = "ErrReplicationRulesViolationErrExternalReservationRefused"
	_APIErrorCode_name_3 = "ErrInvalidRequestErrUnauthorizedAccess"
	_APIErrorCode_name_4 = "ErrSystemTemporarilyDisabled"
)

var (
	_APIErrorCode_index_0 = [...]uint8{0, 17, 44, 78}
	_APIErrorCode_index_1 = [...]uint8{0, 20, 41, 63, 81, 108}
	_APIErrorCode_index_2 = [...]uint8{0, 28, 57}
	_APIErrorCode_index_3 = [...]uint8{0, 17, 38}
)

func (i APIErrorCode) String() string {
	switch {
	case 4011 <= i && i <= 4013:
		i -= 4011
		return _APIErrorCode_name_0[_APIErrorCode_index_0[i]:_APIErrorCode_index_0[i+1]]
	case 4020 <= i && i <= 4024:
		i -= 4020
		return _APIErrorCode_name_1[_APIErrorCode_index_1[i]:_APIErrorCode_index_1[i+1]]
	case 4029 <= i && i <= 4030:
		i -= 4029
		return _APIErrorCode_name_2[_APIErrorCode_index_2[i]:_APIErrorCode_index_2[i+1]]
	case 4400 <= i && i <= 4401:
		i -= 4400
		return _APIErrorCode_name_3[_APIErrorCode_index_3[i]:_APIErrorCode_index_3[i+1]]
	case i == 4503:
		return _APIErrorCode_name_4
	default:
		return "APIErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
